version: "3"
services:
    nginx:
        # 镜像
        image: openresty/openresty:stretch-fat
        #容器名称
        container_name: "openresty"
        #映射端口
        ports:
            - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
            - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/config:/etc/nginx/config"
            - "./nginx/vhost:/etc/nginx/conf.d"
            - "./nginx/cert:/etc/nginx/cert"
            - "./nginx/log:/var/log/nginx"
            - "./nginx/lua:/etc/nginx/lua"
            - "/disk2/www:/usr/share/nginx/html"
        restart: always
        networks:
            - net-app
    php:
        image: registry.cn-guangzhou.aliyuncs.com/ranblogs/php:7.4-fpm
        container_name: "php"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "/disk2/www:/usr/share/nginx/html"
            - "./php/php.ini:/usr/local/etc/php/php.ini"
            - "./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        restart: always
        networks:
            - net-app
    mysql:
        image: mysql
        container_name: "mysql"
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/my.cnf:/etc/my.cnf"
        restart: always
        networks:
            - net-app
    redis:
        image: redis
        container_name: "redis"
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./redis/data:/data"
            - "./redis/logs:/logs"
            - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
        restart: always
        networks:
            - net-app
networks:
    net-app:
        driver: bridge
